{% set name = "xsum" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4bdab1d4b5058ad04c2ae30cc26b3610ef04959d131a60ee8e4e48f896e5129 

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation" 

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=64
    - wheel
    - pybind11 >=2.5.0
    - versioneer >=0.29
  run:
    - python
    - numpy

test:
  imports:
    - xsum
  commands:
    - python -c "from xsum import xsum_small; s = xsum_small(); s.add(1.0); assert s.round() == 1.0"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yafshar/xsum
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Fast Exact Summation Using Small and Large Superaccumulators (XSUM)'
  description: |
    Fast Exact Summation Using Small and Large Superaccumulators (XSUM).
    XSUM is a library for performing exact summation using super-accumulators. 
    It provides methods for exactly summing a set of floating-point numbers, 
    where using a simple summation and the rounding which happens after each 
    addition could be an important factor in many applications.
    The main algorithm is taken from the original library 
    [FUNCTIONS FOR EXACT SUMMATION](https://gitlab.com/radfordneal/xsum) 
    described in the paper 
    "Fast Exact Summation Using Small and Large Superaccumulators," by Radford 
    M. Neal.
  dev_url: https://github.com/yafshar/xsum  

extra:
  recipe-maintainers:
    - yafshar
