{% set name = "xsum" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b064a7319020f96e5d97ff3687d0ee78fe1012468cca132014cc0b929ca78ea0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pybind11
  run:
    - python
    - pybind11
    - numpy

test:
  imports:
    - xsum

about:
  home: https://github.com/yafshar/xsum
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Fast Exact Summation Using Small and Large Superaccumulators (XSUM)'
  description: |
    Fast Exact Summation Using Small and Large Superaccumulators (XSUM).
    XSUM is a library for performing exact summation using super-accumulators. 
    It provides methods for exactly summing a set of floating-point numbers, 
    where using a simple summation and the rounding which happens after each 
    addition could be an important factor in many applications.
    The main algorithm is taken from the original library 
    [FUNCTIONS FOR EXACT SUMMATION](https://gitlab.com/radfordneal/xsum) 
    described in the paper 
    "Fast Exact Summation Using Small and Large Superaccumulators," by Radford 
    M. Neal.
  dev_url: https://github.com/yafshar/xsum

extra:
  recipe-maintainers:
    - yafshar
